#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "endi"
name = "enDI"
description.en = "Comptability software for CAE companies (french Communauté d'Activité et d'Emploi)"
description.fr = "Progiciel de gestion comptable à l'usage des CAE (Communauté d'Activité et d'Emploi)"

version = "6.5.4~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "AGPL-3.0"
website = "https://endi.coop"
demo = "https://demo.endi.coop"
admindoc = "https://framagit.org/endi/endi"
userdoc = "https://doc.endi.coop"
code = "https://framagit.org/endi/endi"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://framagit.org/endi/endi/-/archive/8d2d1e9cbc495dd48712d380c9f039a4e5b877dc/endi-8d2d1e9cbc495dd48712d380c9f039a4e5b877dc.tar.gz"
    sha256 = "16fdee654c59c1ce1f914ca5a620fb9cebd3d2bd5e03e9d4442e68a5daf559ae"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    admin.url = "/admin"

    [resources.apt]
    packages = [
        "mariadb_server",
        "python3-pip",
        "python3-venv",
        "cython3",
        "npm",
        "python3-mysqldb",
        "libmariadb-dev-compat",
        "mariadb-client",
        "libjpeg-dev",
        "libfreetype6",
        "libfreetype6-dev",
        "libssl-dev",
        "libxml2-dev",
        "zlib1g-dev",
        "libxslt1-dev",
        "libcairo2",
        "libpango-1.0-0",
        "libpangocairo-1.0-0",
    ]

    [resources.database]
    type = "mysql"
