#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "caerp"
name = "CAERP"
description.en = "Comptability software for CAE companies (french Communauté d'Activité et d'Emploi), the software behind enDi and MoOGLI"
description.fr = "Progiciel de gestion comptable à l'usage des CAE (Communauté d'Activité et d'Emploi), le logiciel de enDi et MoOGLI"

version = "2024.07.05~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "AGPL-3.0"
website = "https://endi.coop"
demo = "https://demo.endi.coop"
userdoc = "https://doc.endi.coop"
code = "https://framagit.org/caerp/caerp"

[integration]
yunohost = ">= 11.2.12"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://framagit.org/caerp/caerp/-/archive/34ed0cc755e66d7150b263d8b2f9ff4881624271/endi-34ed0cc755e66d7150b263d8b2f9ff4881624271.tar.bz2"
    sha256 = "c98e7210b320b5980846e9f08fe9fdf5a9eee78077e29728914cff0f71a568c7"
    autoupdate.strategy = "latest_gitlab_commit"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    admin.url = "/admin"

    [resources.apt]
    packages = [
        "mariadb-server",
        "mariadb-client",
        # "redis-server",

        "build-essential",
        "fonts-open-sans",
        "libcairo2",
        "libfreetype6-dev",
        "libfreetype6",
        "libgdk-pixbuf-2.0-0",
        "libglib2.0-dev",
        "libjpeg-dev",
        "libmariadb-dev",
        "libmariadb-dev-compat",
        "libpango-1.0-0",
        "libpangocairo-1.0-0",
        "libssl-dev",
        "libxml2-dev",
        "libxslt1-dev",
        "python3-mysqldb",
        "python3-pip",
        "python3-venv",
        "zlib1g-dev",
    ]

    [resources.database]
    type = "mysql"
