#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "endi"
name = "enDI"
description.en = "Comptability software for CAE companies (french Communauté d'Activité et d'Emploi)"
description.fr = "Progiciel de gestion comptable à l'usage des CAE (Communauté d'Activité et d'Emploi)"

version = "6.6.4~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "AGPL-3.0"
website = "https://endi.coop"
demo = "https://demo.endi.coop"
admindoc = "https://framagit.org/endi/endi"
userdoc = "https://doc.endi.coop"
code = "https://framagit.org/endi/endi"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://framagit.org/endi/endi/-/archive/ea2d73983d1b4f55201cb606dce5b58bc30a0553/endi-ea2d73983d1b4f55201cb606dce5b58bc30a0553.tar.bz2"
    sha256 = "6a7983bca4d3b64d6a5df1425c1abae3748247eab52222430cbb1c85284ebef6"
    autoupdate.strategy = "latest_gitlab_commit"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    admin.url = "/admin"

    [resources.apt]
    packages = [
        "mariadb-server",
        "python3-pip",
        "python3-venv",
        "cython3",
        "npm",
        "python3-mysqldb",
        "libmariadb-dev-compat",
        "mariadb-client",
        "libjpeg-dev",
        "libfreetype6",
        "libfreetype6-dev",
        "libssl-dev",
        "libxml2-dev",
        "zlib1g-dev",
        "libxslt1-dev",
        "libcairo2",
        "libpango-1.0-0",
        "libpangocairo-1.0-0",
    ]

    [resources.database]
    type = "mysql"
